# model vars
INSTRUMENTS = {
    'indices': [
        'NAS100',
        'US30',
        'AUS200',
        'UK100',
        'GER30',
        'SPX500',
        'JPN225',
        'EUSTX50',
        'ESP35',
        'NGAS',
        'XAU/USD',
        'XAG/USD',
        'USOil',
        'EUR/USD',
        'GBP/USD',
        'EUR/GBP'
    ],
    'forex': [
        'EUR/USD',
        'GBP/USD',
        'EUR/GBP',
        'USD/CHF',
        'GBP/CHF',
        'EUR/CHF'
    ],
    'crypto': [
        'BTC/USD',
        'BCH/USD',
        'ETH/USD',
        'LTC/USD',
        'XRP/USD',
        'EOS/USD',
        'XLM/USD'
    ]
}

NAIVE_LIST = [
    'NAS100',
    'US30',
    'SPX500',
    'UK100',
    'GER30',
    'AUS200',
    'ESP35',
    'EUR/USD',
    'GBP/USD',
    'EUR/GBP'
]

DARWINEX_TRANSLATION = {
    "US30": "WS30m",
    "AUS200": "AUS200",
    "NAS100": "NDXm",
    "UK100": "UK100",
    "SPX500": "SPXm",
    "GER30": "GDAXIm",
    "JPN225": "J225",
    "EUSTX50": "STOXX50E",
    "ESP35": "SPN35",
    "EUR/USD": "EURUSD",
    "EUR/GBP": "EURGBP",
    "GBP/USD": "GBPUSD",
    "USOil": "XTIUSD",
    "NGAS": "XNGUSD",
    "XAG/USD": "XAGUSD",
    "XAU/USD": "XAUUSD"
}

TARGET = 'target'
TIMESTAMP = 'date'

COLS_TO_EXCLUDE = [
#     'bidopen',
#     'bidclose',
#     'bidhigh',
#     'bidlow',
    'hour',
    'askopen',
    'change_no',
    'start_price',
    'stop_price',
    'start_date',
    'stop_date',
#     'askclose',
    'askhigh',
    'asklow',
    'tickqty',
    'instrument',
    'rsi_pct_change',
    'fourteen_period_forecast',
    'tmp_date',
    'vwap',
    'ema',
    'sar',
    'wma',
    'upperband',
    'middleband',
    'lowerband',
    'diff_vwap',
    'diff_upperband',
    'diff_middleband',
    'diff_lowerband',
    'ad',
    'adosc',
    'ratio_ad',
    'ratio_adosc',
    'diff_askopen',
    'diff_askhigh',
    'diff_asklow',
    'avgprice',
    'medprice',
    'typprice',
    'wclprice',
    'kama',
    'mama',
    'fama',
    'dema',
    't3',
    'sd',
    'linearreg',
    'min',
    'max',
    'ratio_sd',
    'diff_min',
    'diff_max',
    'ratio_linearreg'
]
# COLS_TO_EXCLUDE = [
# #     'change_no',
# #     'final_decision',
#     'start_timestamp',
#     'stop_timestamp',
#     'count_timestamp',
#     'askclose',
#     'asklast',
#     'final_decision',
#     'bidopen',
#     'bidclose',
#     'bidlast',
#     'bidhigh',
#     'bidlow',
#     'askopen',
#     'askhigh',
#     'asklow',
#     'tickqty',
#     'yesterday_bidopen',
#     'yesterday_bidclose',
#     'yesterday_bidhigh',
#     'yesterday_bidlow',
#     'yesterday_askopen',
#     'yesterday_askclose',
#     'yesterday_askhigh',
#     'yesterday_asklow',
#     'yesterday_tickqty',
#     'yesterday_final_decision',
#     'yesterday_instrument',
#     'last_hour_bidopen',
#     'last_hour_bidclose',
#     'last_hour_bidhigh',
#     'last_hour_bidlow',
#     'last_hour_askopen',
#     'last_hour_askclose',
#     'last_hour_askhigh',
#     'last_hour_asklow',
#     'last_hour_tickqty',
#     'last_hour_final_decision',
#     'last_hour_instrument'
# ]

CATEGORICAL_COLS = [
    'macd_interpreted',
    'rsi_interpreted',
    'bop_interpreted',
    'yesterday_macd_interpreted',
    'yesterday_rsi_interpreted',
    'yesterday_bop_interpreted',
    'last_hour_macd_interpreted',
    'last_hour_rsi_interpreted',
    'last_hour_bop_interpreted',
    'instrument'
]

EXCLUDE_FROM_AGG = [
    'change_no',
    'date',
    'askclose',
    'askclose_lead',
    'decision',
    'askhigh_lead',
    'asklow_lead',
    'second_decision'
]

CHART_PATTERNS = [
    'CDL3INSIDE',
    'CDL3LINESTRIKE',
    'CDL3OUTSIDE',
    'CDL3WHITESOLDIERS',
    'CDLABANDONEDBABY',
    'CDLADVANCEBLOCK',
    'CDLBELTHOLD',
    'CDLCLOSINGMARUBOZU',
    'CDLDARKCLOUDCOVER',
    'CDLDOJI',
    'CDLDOJISTAR',
    'CDLDRAGONFLYDOJI',
    'CDLENGULFING',
    'CDLEVENINGDOJISTAR',
    'CDLEVENINGSTAR',
    'CDLGAPSIDESIDEWHITE',
    'CDLGRAVESTONEDOJI',
    'CDLHAMMER',
    'CDLHANGINGMAN',
    'CDLHARAMI',
    'CDLHARAMICROSS',
    'CDLHIGHWAVE',
    'CDLHIKKAKE',
    'CDLHIKKAKEMOD',
    'CDLIDENTICAL3CROWS',
    'CDLINNECK',
    'CDLINVERTEDHAMMER',
    'CDLKICKINGBYLENGTH',
    'CDLLONGLEGGEDDOJI',
    'CDLLONGLINE',
    'CDLMARUBOZU',
    'CDLMATCHINGLOW',
    'CDLMORNINGDOJISTAR',
    'CDLMORNINGSTAR',
    'CDLONNECK',
    'CDLPIERCING',
    'CDLRICKSHAWMAN',
    'CDLSEPARATINGLINES',
    'CDLSHOOTINGSTAR',
    'CDLSHORTLINE',
    'CDLSPINNINGTOP',
    'CDLSTALLEDPATTERN',
    'CDLSTICKSANDWICH',
    'CDLTAKURI',
    'CDLTHRUSTING',
    'CDLXSIDEGAP3METHODS'
]

OLD_LSTM_COLS=[
    'askopen', 'askclose', 'askhigh', 'asklow', 'tickqty', 'date', 'instrument', 'rsi', 'rsi_pct_change', 'cci', 'cmo', 'ppo', 'lr_slope', 'correl', 'beta', 'macd', 'macdsignal', 'macdhist', 'adxr', 'bop', 'mfi', 'ad', 'adosc', 'cdl3inside', 'cdl3linestrike', 'cdl3outside', 'cdl3whitesoldiers', 'cdlabandonedbaby', 'cdladvanceblock', 'cdlbelthold', 'cdlclosingmarubozu', 'cdldarkcloudcover', 'cdldoji', 'cdldojistar', 'cdldragonflydoji', 'cdlengulfing',
    'cdleveningdojistar', 'cdleveningstar', 'cdlgapsidesidewhite', 'cdlgravestonedoji', 'cdlhammer', 'cdlhangingman',
     'cdlharami', 'cdlharamicross', 'cdlhighwave', 'cdlhikkake', 'cdlhikkakemod', 'cdlidentical3crows', 'cdlinneck',
    'cdlinvertedhammer', 'cdlkickingbylength', 'cdllongleggeddoji', 'cdllongline', 'cdlmarubozu', 'cdlmatchinglow', 'cdlmorningdojistar', 'cdlmorningstar', 'cdlonneck', 'cdlpiercing', 'cdlrickshawman', 'cdlseparatinglines', 'cdlshootingstar', 'cdlshortline', 'cdlspinningtop', 'cdlstalledpattern', 'cdlsticksandwich', 'cdltakuri', 'cdlthrusting', 'cdlxsidegap3methods', 'natr', 'ht_dcperiod', 'five_period_sd', 'fourteen_period_forecast', 'rocp', 'upperband', 'middleband', 'lowerband', 'tmp_date', 'vwap', 'ema', 'sar', 'wma', 'diff_askclose', 'diff_askopen', 'diff_askhigh', 'diff_asklow', 'diff_tickqty', 'diff_vwap', 'diff_upperband', 'diff_lowerband', 'diff_middleband', 'diff_ad', 'diff_adosc', 'diff_ema', 'diff_sar', 'diff_wma', 'ratio_askopen', 'ratio_askhigh', 'ratio_asklow', 'ratio_tickqty', 'ratio_vwap', 'ratio_upperband', 'ratio_lowerband', 'ratio_middleband', 'ratio_ad', 'ratio_adosc', 'ratio_ema', 'ratio_sar', 'ratio_wma'
]
